//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.10.18 at 01:15:37 PM IST 
//


package com.camel.integration;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="Customers">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="Customer" maxOccurs="unbounded">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;sequence>
 *                             &lt;element name="CompanyName" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                             &lt;element name="ContactName" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                             &lt;element name="ContactTitle" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                             &lt;element name="Phone" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                             &lt;element name="FullAddress">
 *                               &lt;complexType>
 *                                 &lt;complexContent>
 *                                   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                                     &lt;sequence>
 *                                       &lt;element name="Address" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                                       &lt;element name="City" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                                       &lt;element name="Region" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                                       &lt;element name="PostalCode" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *                                       &lt;element name="Country" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                                     &lt;/sequence>
 *                                   &lt;/restriction>
 *                                 &lt;/complexContent>
 *                               &lt;/complexType>
 *                             &lt;/element>
 *                           &lt;/sequence>
 *                           &lt;attribute name="CustomerID" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="Orders">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="Order" maxOccurs="unbounded">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;sequence>
 *                             &lt;element name="CustomerID" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                             &lt;element name="EmployeeID" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *                             &lt;element name="OrderDate" type="{http://www.w3.org/2001/XMLSchema}dateTime"/>
 *                             &lt;element name="RequiredDate" type="{http://www.w3.org/2001/XMLSchema}dateTime"/>
 *                             &lt;element name="ShipInfo">
 *                               &lt;complexType>
 *                                 &lt;complexContent>
 *                                   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                                     &lt;sequence>
 *                                       &lt;element name="ShipVia" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *                                       &lt;element name="Freight" type="{http://www.w3.org/2001/XMLSchema}double"/>
 *                                       &lt;element name="ShipName" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                                       &lt;element name="ShipAddress" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                                       &lt;element name="ShipCity" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                                       &lt;element name="ShipRegion" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                                       &lt;element name="ShipPostalCode" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *                                       &lt;element name="ShipCountry" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                                     &lt;/sequence>
 *                                     &lt;attribute name="ShippedDate" type="{http://www.w3.org/2001/XMLSchema}dateTime" />
 *                                   &lt;/restriction>
 *                                 &lt;/complexContent>
 *                               &lt;/complexType>
 *                             &lt;/element>
 *                           &lt;/sequence>
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "customers",
    "orders"
})
@XmlRootElement(name = "Root")
public class Root {

    @XmlElement(name = "Customers", required = true)
    protected Root.Customers customers;
    @XmlElement(name = "Orders", required = true)
    protected Root.Orders orders;

    /**
     * Gets the value of the customers property.
     * 
     * @return
     *     possible object is
     *     {@link Root.Customers }
     *     
     */
    public Root.Customers getCustomers() {
        return customers;
    }

    /**
     * Sets the value of the customers property.
     * 
     * @param value
     *     allowed object is
     *     {@link Root.Customers }
     *     
     */
    public void setCustomers(Root.Customers value) {
        this.customers = value;
    }

    /**
     * Gets the value of the orders property.
     * 
     * @return
     *     possible object is
     *     {@link Root.Orders }
     *     
     */
    public Root.Orders getOrders() {
        return orders;
    }

    /**
     * Sets the value of the orders property.
     * 
     * @param value
     *     allowed object is
     *     {@link Root.Orders }
     *     
     */
    public void setOrders(Root.Orders value) {
        this.orders = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="Customer" maxOccurs="unbounded">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;sequence>
     *                   &lt;element name="CompanyName" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                   &lt;element name="ContactName" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                   &lt;element name="ContactTitle" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                   &lt;element name="Phone" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                   &lt;element name="FullAddress">
     *                     &lt;complexType>
     *                       &lt;complexContent>
     *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                           &lt;sequence>
     *                             &lt;element name="Address" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                             &lt;element name="City" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                             &lt;element name="Region" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                             &lt;element name="PostalCode" type="{http://www.w3.org/2001/XMLSchema}int"/>
     *                             &lt;element name="Country" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                           &lt;/sequence>
     *                         &lt;/restriction>
     *                       &lt;/complexContent>
     *                     &lt;/complexType>
     *                   &lt;/element>
     *                 &lt;/sequence>
     *                 &lt;attribute name="CustomerID" type="{http://www.w3.org/2001/XMLSchema}string" />
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "customer"
    })
    public static class Customers {

        @XmlElement(name = "Customer", required = true)
        protected List<Root.Customers.Customer> customer;

        /**
         * Gets the value of the customer property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the customer property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getCustomer().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link Root.Customers.Customer }
         * 
         * 
         */
        public List<Root.Customers.Customer> getCustomer() {
            if (customer == null) {
                customer = new ArrayList<Root.Customers.Customer>();
            }
            return this.customer;
        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;sequence>
         *         &lt;element name="CompanyName" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *         &lt;element name="ContactName" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *         &lt;element name="ContactTitle" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *         &lt;element name="Phone" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *         &lt;element name="FullAddress">
         *           &lt;complexType>
         *             &lt;complexContent>
         *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *                 &lt;sequence>
         *                   &lt;element name="Address" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *                   &lt;element name="City" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *                   &lt;element name="Region" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *                   &lt;element name="PostalCode" type="{http://www.w3.org/2001/XMLSchema}int"/>
         *                   &lt;element name="Country" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *                 &lt;/sequence>
         *               &lt;/restriction>
         *             &lt;/complexContent>
         *           &lt;/complexType>
         *         &lt;/element>
         *       &lt;/sequence>
         *       &lt;attribute name="CustomerID" type="{http://www.w3.org/2001/XMLSchema}string" />
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "companyName",
            "contactName",
            "contactTitle",
            "phone",
            "fullAddress"
        })
        public static class Customer {

            @XmlElement(name = "CompanyName", required = true)
            protected String companyName;
            @XmlElement(name = "ContactName", required = true)
            protected String contactName;
            @XmlElement(name = "ContactTitle", required = true)
            protected String contactTitle;
            @XmlElement(name = "Phone", required = true)
            protected String phone;
            @XmlElement(name = "FullAddress", required = true)
            protected Root.Customers.Customer.FullAddress fullAddress;
            @XmlAttribute(name = "CustomerID")
            protected String customerID;

            /**
             * Gets the value of the companyName property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getCompanyName() {
                return companyName;
            }

            /**
             * Sets the value of the companyName property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setCompanyName(String value) {
                this.companyName = value;
            }

            /**
             * Gets the value of the contactName property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getContactName() {
                return contactName;
            }

            /**
             * Sets the value of the contactName property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setContactName(String value) {
                this.contactName = value;
            }

            /**
             * Gets the value of the contactTitle property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getContactTitle() {
                return contactTitle;
            }

            /**
             * Sets the value of the contactTitle property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setContactTitle(String value) {
                this.contactTitle = value;
            }

            /**
             * Gets the value of the phone property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getPhone() {
                return phone;
            }

            /**
             * Sets the value of the phone property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setPhone(String value) {
                this.phone = value;
            }

            /**
             * Gets the value of the fullAddress property.
             * 
             * @return
             *     possible object is
             *     {@link Root.Customers.Customer.FullAddress }
             *     
             */
            public Root.Customers.Customer.FullAddress getFullAddress() {
                return fullAddress;
            }

            /**
             * Sets the value of the fullAddress property.
             * 
             * @param value
             *     allowed object is
             *     {@link Root.Customers.Customer.FullAddress }
             *     
             */
            public void setFullAddress(Root.Customers.Customer.FullAddress value) {
                this.fullAddress = value;
            }

            /**
             * Gets the value of the customerID property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getCustomerID() {
                return customerID;
            }

            /**
             * Sets the value of the customerID property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setCustomerID(String value) {
                this.customerID = value;
            }


            /**
             * <p>Java class for anonymous complex type.
             * 
             * <p>The following schema fragment specifies the expected content contained within this class.
             * 
             * <pre>
             * &lt;complexType>
             *   &lt;complexContent>
             *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
             *       &lt;sequence>
             *         &lt;element name="Address" type="{http://www.w3.org/2001/XMLSchema}string"/>
             *         &lt;element name="City" type="{http://www.w3.org/2001/XMLSchema}string"/>
             *         &lt;element name="Region" type="{http://www.w3.org/2001/XMLSchema}string"/>
             *         &lt;element name="PostalCode" type="{http://www.w3.org/2001/XMLSchema}int"/>
             *         &lt;element name="Country" type="{http://www.w3.org/2001/XMLSchema}string"/>
             *       &lt;/sequence>
             *     &lt;/restriction>
             *   &lt;/complexContent>
             * &lt;/complexType>
             * </pre>
             * 
             * 
             */
            @XmlAccessorType(XmlAccessType.FIELD)
            @XmlType(name = "", propOrder = {
                "address",
                "city",
                "region",
                "postalCode",
                "country"
            })
            public static class FullAddress {

                @XmlElement(name = "Address", required = true)
                protected String address;
                @XmlElement(name = "City", required = true)
                protected String city;
                @XmlElement(name = "Region", required = true)
                protected String region;
                @XmlElement(name = "PostalCode")
                protected int postalCode;
                @XmlElement(name = "Country", required = true)
                protected String country;

                /**
                 * Gets the value of the address property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link String }
                 *     
                 */
                public String getAddress() {
                    return address;
                }

                /**
                 * Sets the value of the address property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *     
                 */
                public void setAddress(String value) {
                    this.address = value;
                }

                /**
                 * Gets the value of the city property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link String }
                 *     
                 */
                public String getCity() {
                    return city;
                }

                /**
                 * Sets the value of the city property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *     
                 */
                public void setCity(String value) {
                    this.city = value;
                }

                /**
                 * Gets the value of the region property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link String }
                 *     
                 */
                public String getRegion() {
                    return region;
                }

                /**
                 * Sets the value of the region property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *     
                 */
                public void setRegion(String value) {
                    this.region = value;
                }

                /**
                 * Gets the value of the postalCode property.
                 * 
                 */
                public int getPostalCode() {
                    return postalCode;
                }

                /**
                 * Sets the value of the postalCode property.
                 * 
                 */
                public void setPostalCode(int value) {
                    this.postalCode = value;
                }

                /**
                 * Gets the value of the country property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link String }
                 *     
                 */
                public String getCountry() {
                    return country;
                }

                /**
                 * Sets the value of the country property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *     
                 */
                public void setCountry(String value) {
                    this.country = value;
                }

            }

        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="Order" maxOccurs="unbounded">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;sequence>
     *                   &lt;element name="CustomerID" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                   &lt;element name="EmployeeID" type="{http://www.w3.org/2001/XMLSchema}int"/>
     *                   &lt;element name="OrderDate" type="{http://www.w3.org/2001/XMLSchema}dateTime"/>
     *                   &lt;element name="RequiredDate" type="{http://www.w3.org/2001/XMLSchema}dateTime"/>
     *                   &lt;element name="ShipInfo">
     *                     &lt;complexType>
     *                       &lt;complexContent>
     *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                           &lt;sequence>
     *                             &lt;element name="ShipVia" type="{http://www.w3.org/2001/XMLSchema}int"/>
     *                             &lt;element name="Freight" type="{http://www.w3.org/2001/XMLSchema}double"/>
     *                             &lt;element name="ShipName" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                             &lt;element name="ShipAddress" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                             &lt;element name="ShipCity" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                             &lt;element name="ShipRegion" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                             &lt;element name="ShipPostalCode" type="{http://www.w3.org/2001/XMLSchema}int"/>
     *                             &lt;element name="ShipCountry" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                           &lt;/sequence>
     *                           &lt;attribute name="ShippedDate" type="{http://www.w3.org/2001/XMLSchema}dateTime" />
     *                         &lt;/restriction>
     *                       &lt;/complexContent>
     *                     &lt;/complexType>
     *                   &lt;/element>
     *                 &lt;/sequence>
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "order"
    })
    public static class Orders {

        @XmlElement(name = "Order", required = true)
        protected List<Root.Orders.Order> order;

        /**
         * Gets the value of the order property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the order property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getOrder().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link Root.Orders.Order }
         * 
         * 
         */
        public List<Root.Orders.Order> getOrder() {
            if (order == null) {
                order = new ArrayList<Root.Orders.Order>();
            }
            return this.order;
        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;sequence>
         *         &lt;element name="CustomerID" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *         &lt;element name="EmployeeID" type="{http://www.w3.org/2001/XMLSchema}int"/>
         *         &lt;element name="OrderDate" type="{http://www.w3.org/2001/XMLSchema}dateTime"/>
         *         &lt;element name="RequiredDate" type="{http://www.w3.org/2001/XMLSchema}dateTime"/>
         *         &lt;element name="ShipInfo">
         *           &lt;complexType>
         *             &lt;complexContent>
         *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *                 &lt;sequence>
         *                   &lt;element name="ShipVia" type="{http://www.w3.org/2001/XMLSchema}int"/>
         *                   &lt;element name="Freight" type="{http://www.w3.org/2001/XMLSchema}double"/>
         *                   &lt;element name="ShipName" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *                   &lt;element name="ShipAddress" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *                   &lt;element name="ShipCity" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *                   &lt;element name="ShipRegion" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *                   &lt;element name="ShipPostalCode" type="{http://www.w3.org/2001/XMLSchema}int"/>
         *                   &lt;element name="ShipCountry" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *                 &lt;/sequence>
         *                 &lt;attribute name="ShippedDate" type="{http://www.w3.org/2001/XMLSchema}dateTime" />
         *               &lt;/restriction>
         *             &lt;/complexContent>
         *           &lt;/complexType>
         *         &lt;/element>
         *       &lt;/sequence>
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "customerID",
            "employeeID",
            "orderDate",
            "requiredDate",
            "shipInfo"
        })
        public static class Order {

            @XmlElement(name = "CustomerID", required = true)
            protected String customerID;
            @XmlElement(name = "EmployeeID")
            protected int employeeID;
            @XmlElement(name = "OrderDate", required = true)
            @XmlSchemaType(name = "dateTime")
            protected XMLGregorianCalendar orderDate;
            @XmlElement(name = "RequiredDate", required = true)
            @XmlSchemaType(name = "dateTime")
            protected XMLGregorianCalendar requiredDate;
            @XmlElement(name = "ShipInfo", required = true)
            protected Root.Orders.Order.ShipInfo shipInfo;

            /**
             * Gets the value of the customerID property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getCustomerID() {
                return customerID;
            }

            /**
             * Sets the value of the customerID property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setCustomerID(String value) {
                this.customerID = value;
            }

            /**
             * Gets the value of the employeeID property.
             * 
             */
            public int getEmployeeID() {
                return employeeID;
            }

            /**
             * Sets the value of the employeeID property.
             * 
             */
            public void setEmployeeID(int value) {
                this.employeeID = value;
            }

            /**
             * Gets the value of the orderDate property.
             * 
             * @return
             *     possible object is
             *     {@link XMLGregorianCalendar }
             *     
             */
            public XMLGregorianCalendar getOrderDate() {
                return orderDate;
            }

            /**
             * Sets the value of the orderDate property.
             * 
             * @param value
             *     allowed object is
             *     {@link XMLGregorianCalendar }
             *     
             */
            public void setOrderDate(XMLGregorianCalendar value) {
                this.orderDate = value;
            }

            /**
             * Gets the value of the requiredDate property.
             * 
             * @return
             *     possible object is
             *     {@link XMLGregorianCalendar }
             *     
             */
            public XMLGregorianCalendar getRequiredDate() {
                return requiredDate;
            }

            /**
             * Sets the value of the requiredDate property.
             * 
             * @param value
             *     allowed object is
             *     {@link XMLGregorianCalendar }
             *     
             */
            public void setRequiredDate(XMLGregorianCalendar value) {
                this.requiredDate = value;
            }

            /**
             * Gets the value of the shipInfo property.
             * 
             * @return
             *     possible object is
             *     {@link Root.Orders.Order.ShipInfo }
             *     
             */
            public Root.Orders.Order.ShipInfo getShipInfo() {
                return shipInfo;
            }

            /**
             * Sets the value of the shipInfo property.
             * 
             * @param value
             *     allowed object is
             *     {@link Root.Orders.Order.ShipInfo }
             *     
             */
            public void setShipInfo(Root.Orders.Order.ShipInfo value) {
                this.shipInfo = value;
            }


            /**
             * <p>Java class for anonymous complex type.
             * 
             * <p>The following schema fragment specifies the expected content contained within this class.
             * 
             * <pre>
             * &lt;complexType>
             *   &lt;complexContent>
             *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
             *       &lt;sequence>
             *         &lt;element name="ShipVia" type="{http://www.w3.org/2001/XMLSchema}int"/>
             *         &lt;element name="Freight" type="{http://www.w3.org/2001/XMLSchema}double"/>
             *         &lt;element name="ShipName" type="{http://www.w3.org/2001/XMLSchema}string"/>
             *         &lt;element name="ShipAddress" type="{http://www.w3.org/2001/XMLSchema}string"/>
             *         &lt;element name="ShipCity" type="{http://www.w3.org/2001/XMLSchema}string"/>
             *         &lt;element name="ShipRegion" type="{http://www.w3.org/2001/XMLSchema}string"/>
             *         &lt;element name="ShipPostalCode" type="{http://www.w3.org/2001/XMLSchema}int"/>
             *         &lt;element name="ShipCountry" type="{http://www.w3.org/2001/XMLSchema}string"/>
             *       &lt;/sequence>
             *       &lt;attribute name="ShippedDate" type="{http://www.w3.org/2001/XMLSchema}dateTime" />
             *     &lt;/restriction>
             *   &lt;/complexContent>
             * &lt;/complexType>
             * </pre>
             * 
             * 
             */
            @XmlAccessorType(XmlAccessType.FIELD)
            @XmlType(name = "", propOrder = {
                "shipVia",
                "freight",
                "shipName",
                "shipAddress",
                "shipCity",
                "shipRegion",
                "shipPostalCode",
                "shipCountry"
            })
            public static class ShipInfo {

                @XmlElement(name = "ShipVia")
                protected int shipVia;
                @XmlElement(name = "Freight")
                protected double freight;
                @XmlElement(name = "ShipName", required = true)
                protected String shipName;
                @XmlElement(name = "ShipAddress", required = true)
                protected String shipAddress;
                @XmlElement(name = "ShipCity", required = true)
                protected String shipCity;
                @XmlElement(name = "ShipRegion", required = true)
                protected String shipRegion;
                @XmlElement(name = "ShipPostalCode")
                protected int shipPostalCode;
                @XmlElement(name = "ShipCountry", required = true)
                protected String shipCountry;
                @XmlAttribute(name = "ShippedDate")
                @XmlSchemaType(name = "dateTime")
                protected XMLGregorianCalendar shippedDate;

                /**
                 * Gets the value of the shipVia property.
                 * 
                 */
                public int getShipVia() {
                    return shipVia;
                }

                /**
                 * Sets the value of the shipVia property.
                 * 
                 */
                public void setShipVia(int value) {
                    this.shipVia = value;
                }

                /**
                 * Gets the value of the freight property.
                 * 
                 */
                public double getFreight() {
                    return freight;
                }

                /**
                 * Sets the value of the freight property.
                 * 
                 */
                public void setFreight(double value) {
                    this.freight = value;
                }

                /**
                 * Gets the value of the shipName property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link String }
                 *     
                 */
                public String getShipName() {
                    return shipName;
                }

                /**
                 * Sets the value of the shipName property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *     
                 */
                public void setShipName(String value) {
                    this.shipName = value;
                }

                /**
                 * Gets the value of the shipAddress property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link String }
                 *     
                 */
                public String getShipAddress() {
                    return shipAddress;
                }

                /**
                 * Sets the value of the shipAddress property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *     
                 */
                public void setShipAddress(String value) {
                    this.shipAddress = value;
                }

                /**
                 * Gets the value of the shipCity property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link String }
                 *     
                 */
                public String getShipCity() {
                    return shipCity;
                }

                /**
                 * Sets the value of the shipCity property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *     
                 */
                public void setShipCity(String value) {
                    this.shipCity = value;
                }

                /**
                 * Gets the value of the shipRegion property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link String }
                 *     
                 */
                public String getShipRegion() {
                    return shipRegion;
                }

                /**
                 * Sets the value of the shipRegion property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *     
                 */
                public void setShipRegion(String value) {
                    this.shipRegion = value;
                }

                /**
                 * Gets the value of the shipPostalCode property.
                 * 
                 */
                public int getShipPostalCode() {
                    return shipPostalCode;
                }

                /**
                 * Sets the value of the shipPostalCode property.
                 * 
                 */
                public void setShipPostalCode(int value) {
                    this.shipPostalCode = value;
                }

                /**
                 * Gets the value of the shipCountry property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link String }
                 *     
                 */
                public String getShipCountry() {
                    return shipCountry;
                }

                /**
                 * Sets the value of the shipCountry property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *     
                 */
                public void setShipCountry(String value) {
                    this.shipCountry = value;
                }

                /**
                 * Gets the value of the shippedDate property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link XMLGregorianCalendar }
                 *     
                 */
                public XMLGregorianCalendar getShippedDate() {
                    return shippedDate;
                }

                /**
                 * Sets the value of the shippedDate property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link XMLGregorianCalendar }
                 *     
                 */
                public void setShippedDate(XMLGregorianCalendar value) {
                    this.shippedDate = value;
                }

            }

        }

    }

}
